export const movies = [
  { title: 'Movie 1' },
  { title: 'Movie 2' },
  { title: 'Movie 3' },
  { title: 'Movie 4' },
  { title: 'Movie 5' },
  { title: 'Movie 6' },
  { title: 'Movie 7' },
  { title: 'Movie 8' },
  { title: 'Movie 1' },
  { title: 'Movie 2' },
  { title: 'Movie 3' },
  { title: 'Movie 4' },
  { title: 'Movie 5' },
  { title: 'Movie 6' },
  { title: 'Movie 7' },
  { title: 'Movie 8' },
]

export const concerts = [
  { title: 'Concert 1' },
  { title: 'Concert 2' },
  { title: 'Concert 3' },
  { title: 'Concert 4' },
  { title: 'Concert 5' },
  { title: 'Concert 6' },
  { title: 'Concert 7' },
  { title: 'Concert 8' },
  { title: 'Concert 1' },
  { title: 'Concert 2' },
  { title: 'Concert 3' },
  { title: 'Concert 4' },
  { title: 'Concert 5' },
  { title: 'Concert 6' },
  { title: 'Concert 7' },
  { title: 'Concert 8' },
]

export const sports = [
  { title: 'Sport 1' },
  { title: 'Sport 2' },
  { title: 'Sport 3' },
  { title: 'Sport 4' },
  { title: 'Sport 5' },
  { title: 'Sport 6' },
  { title: 'Sport 7' },
  { title: 'Sport 8' },
  { title: 'Sport 1' },
  { title: 'Sport 2' },
  { title: 'Sport 3' },
  { title: 'Sport 4' },
  { title: 'Sport 5' },
  { title: 'Sport 6' },
  { title: 'Sport 7' },
  { title: 'Sport 8' },
]

export const theatre = [
  { title: 'Theatre 1' },
  { title: 'Theatre 2' },
  { title: 'Theatre 3' },
  { title: 'Theatre 4' },
  { title: 'Theatre 5' },
  { title: 'Theatre 6' },
  { title: 'Theatre 7' },
  { title: 'Theatre 8' },
  { title: 'Theatre 1' },
  { title: 'Theatre 2' },
  { title: 'Theatre 3' },
  { title: 'Theatre 4' },
  { title: 'Theatre 5' },
  { title: 'Theatre 6' },
  { title: 'Theatre 7' },
  { title: 'Theatre 8' },
]

export const sortOptions = [
  { value: 'latest', label: 'Latest' },
  { value: 'date', label: 'Date' },
  { value: 'time', label: 'Time' },
  { value: 'place', label: 'Place' },
  { value: 'price', label: 'Price' },
]
